version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=birdgang
      - MYSQL_DATABASE=birdgang
    ports:
      - "3306:3306"
